### PR TITLE
upgrade openstack pike to train. Closes #57

### LINKED ISSUE #57: Upgrade openstack pike to train - dockerhost

### PR DESCRIPTION
**Pull request by Ilavarasi1**

### CODE REVIEW

**Comment by Ilavarasi1** [comment]
It would be better to have the repo for a while. Just incase - for rollback. If we remove then we can't get them back since mirrors are not there anymore .

**Comment by tourunen** [comment]
To be able to install old pike packages, I suppose we would need to use the CentOS Vault archive

http://vault.centos.org/7.5.1804/cloud/x86_64/openstack-pike/

**Comment by Ilavarasi1** [comment]
Thanks Olli. Changed it!

**Comment by tourunen** [comment]
Closing as this was dealt with #59

**Pull request closed without merging**
